# Generated by Django 2.2.4 on 2019-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
    ]
